import 'dotenv/config';
import { db } from './index';
import { subscriptionProviders } from './schema';

const providers = [
  {
    name: 'Netflix',
    categoryId: 1,
    logoUrl: 'netflix-logo.png',
    websiteUrl: 'https://www.netflix.com',
    cancelUrl: 'https://www.netflix.com/cancelplan',
    isPopular: true,
  },
  {
    name: 'Spotify',
    categoryId: 1,
    logoUrl: 'spotify-logo.png',
    websiteUrl: 'https://www.spotify.com',
    cancelUrl: 'https://www.spotify.com/account/subscription',
    isPopular: true,
  },
  {
    name: 'YouTube Premium',
    categoryId: 1,
    logoUrl: 'youtube-premium-logo.png',
    websiteUrl: 'https://www.youtube.com/premium',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    isPopular: true,
  },
  {
    name: 'Canva',
    categoryId: 2,
    logoUrl: 'canva-pro-logo.png',
    websiteUrl: 'https://www.canva.com',
    cancelUrl: 'https://www.canva.com/settings/billing-and-plans',
    isPopular: true,
  },
  {
    name: 'Adobe Creative Cloud',
    categoryId: 2,
    logoUrl: 'adobe-creative-cloud-logo.png',
    websiteUrl: 'https://www.adobe.com/creativecloud.html',
    cancelUrl: 'https://account.adobe.com/plans',
    isPopular: true,
  },
  {
    name: 'Microsoft 365',
    categoryId: 2,
    logoUrl: 'microsoft-365-logo.png',
    websiteUrl: 'https://www.microsoft.com/microsoft-365',
    cancelUrl: 'https://account.microsoft.com/services',
    isPopular: true,
  },
  {
    name: 'Google One',
    categoryId: 5,
    logoUrl: 'google-one-logo.png',
    websiteUrl: 'https://one.google.com',
    cancelUrl: 'https://one.google.com/settings',
    isPopular: true,
  },
  {
    name: 'Dropbox',
    categoryId: 2,
    logoUrl: 'dropbox-logo.png',
    websiteUrl: 'https://www.dropbox.com',
    cancelUrl: 'https://www.dropbox.com/account/plan',
    isPopular: true,
  },
  {
    name: 'Notion',
    categoryId: 2,
    logoUrl: 'notion-plus-logo.png',
    websiteUrl: 'https://www.notion.so',
    cancelUrl: 'https://www.notion.so/help/billing',
    isPopular: true,
  },
  {
    name: 'ChatGPT',
    categoryId: 2,
    logoUrl: 'chatgpt-logo.png',
    websiteUrl: 'https://chatgpt.com',
    cancelUrl: 'https://chatgpt.com/#settings/Subscription',
    isPopular: true,
  },
  {
    name: 'Shahid',
    categoryId: 1,
    logoUrl: 'shahid-logo.png',
    websiteUrl: 'https://shahid.mbc.net',
    cancelUrl: 'https://shahid.mbc.net/account',
    isPopular: true,
  },
  {
    name: 'OSN+',
    categoryId: 1,
    logoUrl: 'osn-plus-logo.png',
    websiteUrl: 'https://www.osnplus.com',
    cancelUrl: 'https://www.osnplus.com',
    isPopular: true,
  },
  {
    name: 'STARZPLAY',
    categoryId: 1,
    logoUrl: 'starzplay-logo.png',
    websiteUrl: 'https://starzplay.com',
    cancelUrl: 'https://starzplay.com/account',
    isPopular: true,
  },
  {
    name: 'Amazon Prime',
    categoryId: 1,
    logoUrl: 'amazon-prime-logo.png',
    websiteUrl: 'https://www.amazon.com/prime',
    cancelUrl: 'https://www.amazon.com/amazonprime',
    isPopular: true,
  },
  {
    name: 'Apple Music',
    categoryId: 1,
    logoUrl: 'apple-music-logo.png',
    websiteUrl: 'https://music.apple.com',
    cancelUrl: 'https://support.apple.com/billing',
    isPopular: true,
  },
  {
    name: 'Disney+',
    categoryId: 1,
    logoUrl: 'disney-plus-logo.png',
    websiteUrl: 'https://www.disneyplus.com',
    cancelUrl: 'https://www.disneyplus.com/account',
    isPopular: true,
  },
  {
    name: 'Deezer',
    categoryId: 1,
    logoUrl: 'deezer-logo.png',
    websiteUrl: 'https://www.deezer.com',
    cancelUrl: 'https://www.deezer.com/account',
    isPopular: false,
  },
  {
    name: 'Crunchyroll',
    categoryId: 1,
    logoUrl: 'crunchyroll-logo.png',
    websiteUrl: 'https://www.crunchyroll.com',
    cancelUrl: 'https://www.crunchyroll.com/account/membership',
    isPopular: false,
  },
  {
    name: 'Twitch Turbo',
    categoryId: 1,
    logoUrl: 'twitch-turbo-logo.png',
    websiteUrl: 'https://www.twitch.tv/turbo',
    cancelUrl: 'https://www.twitch.tv/subscriptions',
    isPopular: false,
  },
  {
    name: 'Jahez',
    categoryId: 1,
    logoUrl: 'jahez-logo.png',
    websiteUrl: 'https://jahez.net',
    cancelUrl: 'https://jahez.net',
    isPopular: true,
  },
  {
    name: 'HungerStation',
    categoryId: 1,
    logoUrl: 'hungerstation-logo.png',
    websiteUrl: 'https://hungerstation.com',
    cancelUrl: 'https://hungerstation.com',
    isPopular: true,
  },
  {
    name: 'STC TV',
    categoryId: 1,
    logoUrl: 'stc-tv-logo.png',
    websiteUrl: 'https://www.stctv.com',
    cancelUrl: 'https://www.stctv.com',
    isPopular: true,
  },
  {
    name: 'Thmanyah',
    categoryId: 1,
    logoUrl: 'thmanyah-logo.png',
    websiteUrl: 'https://thmanyah.com',
    cancelUrl: 'https://thmanyah.com',
    isPopular: true,
  },

  {
    name: 'Slack',
    categoryId: 2,
    logoUrl: 'slack-logo.png',
    websiteUrl: 'https://slack.com',
    cancelUrl: 'https://slack.com/help/articles/218915077',
    isPopular: true,
  },
  {
    name: 'Zoom',
    categoryId: 2,
    logoUrl: 'zoom-logo.png',
    websiteUrl: 'https://zoom.us',
    cancelUrl: 'https://zoom.us/billing',
    isPopular: true,
  },
  {
    name: 'Figma',
    categoryId: 2,
    logoUrl: 'figma-logo.png',
    websiteUrl: 'https://www.figma.com',
    cancelUrl: 'https://www.figma.com/files/team/settings/billing',
    isPopular: true,
  },
  {
    name: 'GitHub Pro',
    categoryId: 2,
    logoUrl: 'github-pro-logo.png',
    websiteUrl: 'https://github.com',
    cancelUrl: 'https://github.com/settings/billing',
    isPopular: true,
  },
  {
    name: 'Grammarly',
    categoryId: 2,
    logoUrl: 'grammarly-logo.png',
    websiteUrl: 'https://www.grammarly.com',
    cancelUrl: 'https://account.grammarly.com/subscription',
    isPopular: false,
  },
  {
    name: 'Trello',
    categoryId: 2,
    logoUrl: 'trello-logo.png',
    websiteUrl: 'https://trello.com',
    cancelUrl: 'https://trello.com/billing',
    isPopular: false,
  },
  {
    name: 'Monday.com',
    categoryId: 2,
    logoUrl: 'monday-logo.png',
    websiteUrl: 'https://monday.com',
    cancelUrl: 'https://monday.com',
    isPopular: false,
  },
  {
    name: 'Asana',
    categoryId: 2,
    logoUrl: 'asana-logo.png',
    websiteUrl: 'https://asana.com',
    cancelUrl: 'https://app.asana.com/admin/billing',
    isPopular: false,
  },
  {
    name: 'Jira',
    categoryId: 2,
    logoUrl: 'jira-logo.png',
    websiteUrl: 'https://www.atlassian.com/software/jira',
    cancelUrl: 'https://admin.atlassian.com/billing',
    isPopular: false,
  },
  {
    name: 'Adobe Acrobat',
    categoryId: 2,
    logoUrl: 'adobe-acrobat-logo.png',
    websiteUrl: 'https://www.adobe.com/acrobat.html',
    cancelUrl: 'https://account.adobe.com/plans',
    isPopular: false,
  },
  {
    name: 'Salla',
    categoryId: 2,
    logoUrl: 'salla-logo.png',
    websiteUrl: 'https://salla.sa',
    cancelUrl: 'https://salla.sa',
    isPopular: true,
  },
  {
    name: 'Zid',
    categoryId: 2,
    logoUrl: 'zid-logo.png',
    websiteUrl: 'https://zid.sa',
    cancelUrl: 'https://zid.sa',
    isPopular: true,
  },

  {
    name: 'Gemini',
    categoryId: 2,
    logoUrl: 'gemini-logo.png',
    websiteUrl: 'https://gemini.google.com',
    cancelUrl: 'https://one.google.com/settings',
    isPopular: true,
  },
  {
    name: 'Claude',
    categoryId: 2,
    logoUrl: 'claude-logo.png',
    websiteUrl: 'https://claude.ai',
    cancelUrl: 'https://claude.ai/settings/billing',
    isPopular: true,
  },

  {
    name: 'Udemy',
    categoryId: 3,
    logoUrl: 'udemy-logo.png',
    websiteUrl: 'https://www.udemy.com',
    cancelUrl: 'https://www.udemy.com/user/manage-subscriptions',
    isPopular: true,
  },
  {
    name: 'LinkedIn Learning',
    categoryId: 3,
    logoUrl: 'linkedin-learning-logo.png',
    websiteUrl: 'https://www.linkedin.com/learning',
    cancelUrl: 'https://www.linkedin.com/psettings/premium-subscription',
    isPopular: false,
  },
  {
    name: 'Quizlet',
    categoryId: 3,
    logoUrl: 'quizlet-logo.png',
    websiteUrl: 'https://quizlet.com',
    cancelUrl: 'https://quizlet.com/settings',
    isPopular: false,
  },

  {
    name: 'Calm',
    categoryId: 4,
    logoUrl: 'calm-logo.png',
    websiteUrl: 'https://www.calm.com',
    cancelUrl: 'https://www.calm.com/settings',
    isPopular: false,
  },
  {
    name: 'Headspace',
    categoryId: 4,
    logoUrl: 'headspace-logo.png',
    websiteUrl: 'https://www.headspace.com',
    cancelUrl: 'https://www.headspace.com/subscription/manage',
    isPopular: false,
  },
  {
    name: 'MyFitnessPal',
    categoryId: 4,
    logoUrl: 'myfitnesspal-logo.png',
    websiteUrl: 'https://www.myfitnesspal.com',
    cancelUrl: 'https://www.myfitnesspal.com/premium/account',
    isPopular: false,
  },
  {
    name: 'Fitbit Premium',
    categoryId: 4,
    logoUrl: 'fitbit-premium-logo.png',
    websiteUrl: 'https://www.fitbit.com/products/services/premium',
    cancelUrl: 'https://www.fitbit.com/settings',
    isPopular: false,
  },

  {
    name: 'iCloud+',
    categoryId: 5,
    logoUrl: 'icloud-plus-logo.png',
    websiteUrl: 'https://www.icloud.com',
    cancelUrl: 'https://support.apple.com/billing',
    isPopular: true,
  },
  {
    name: 'Ninja',
    categoryId: 5,
    logoUrl: 'ninja-logo.png',
    websiteUrl:
      'https://ananinja.com/sa/ar?gad_source=1&gad_campaignid=21368424669&gbraid=0AAAAAoaKhgTijYkEkwIiST0gKq8MitE5w&gclid=Cj0KCQjwoMXQBhDcARIsAH-eEtuELKb0ersQMMG0mhuVvFrz-WzYH9IVV6GWl0l8hueGXiby5-dT-_saAv2ZEALw_wcB',
    cancelUrl:
      'https://ananinja.com/sa/ar?gad_source=1&gad_campaignid=21368424669&gbraid=0AAAAAoaKhgTijYkEkwIiST0gKq8MitE5w&gclid=Cj0KCQjwoMXQBhDcARIsAH-eEtuELKb0ersQMMG0mhuVvFrz-WzYH9IVV6GWl0l8hueGXiby5-dT-_saAv2ZEALw_wcB',
    isPopular: true,
  },
];

async function seedProviders() {
  for (const provider of providers) {
    await db
      .insert(subscriptionProviders)
      .values(provider)
      .onConflictDoUpdate({
        target: subscriptionProviders.name,
        set: {
          categoryId: provider.categoryId,
          logoUrl: provider.logoUrl,
          websiteUrl: provider.websiteUrl,
          cancelUrl: provider.cancelUrl,
          isPopular: provider.isPopular,
        },
      });
  }

  console.log('Subscription providers seeded successfully');
}

seedProviders()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Failed to seed providers:', error);
    process.exit(1);
  });
